{
 "title": "SCCM logs",
 "tags": [
  "logs",
  "sccm",
  "windows"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   {
    "name": "hostname",
    "label": "Host Name",
    "query": {}
   },
   {
    "name": "component",
    "label": "Component",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Hosts",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\"} | unpack [$__auto]))",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top Components",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(component) (count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\", component=~\"$component\"} | unpack | component != `` [$__auto]))",
     "legendFormat": "{{ component }}"
    }
   ]
  },
  {
   "title": "Parsing Level",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\", component=~\"$component\"} | unpack | component = `` [$__auto]))",
     "legendFormat": "Unparsed"
    },
    {
     "expr": "sum(count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\"} | unpack | component != `` [$__auto]))",
     "legendFormat": "Parsed"
    }
   ]
  },
  {
   "title": "Entries by host timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\", component=~\"$component\"} | unpack [$__auto]))",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Entries by component timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(component) (count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\", component=~\"$component\"} | unpack [$__auto]))",
     "legendFormat": "{{ component  }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Unparsed entries by host and file",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(filename, hostname) (count_over_time({job=\"file\", app=\"sccm\", hostname=~\"$hostname\"} | unpack | component = `` [$__auto]))",
     "legendFormat": "{{hostname}}: {{filename}}"
    }
   ]
  },
  {
   "title": "Latest entries",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{job=\"file\", app=\"sccm\", hostname=~\"$hostname\", component=~\"$component\"} | unpack | regexp `<!\\[LOG\\[(?P<message>.+)\\]LOG\\]!>` | regexp `(?P<message>.+)  \\$\\$<` | line_format `{{ .hostname }} ({{ .component }}): {{ .message }}`"
    }
   ]
  }
 ]
}